# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box            = "ubuntu/trusty64"
    config.vm.hostname       = "nothing"
    config.ssh.forward_x11   = true
    config.ssh.forward_agent = true
    config.vm.network "forwarded_port", guest: 8000, host: 8000

    config.vm.provider "virtualbox" do |v|
        v.cpus = 1
        v.memory = 1024
        v.name = "nothing"
    end

    config.vm.provision :shell, :path => "root_setup.sh"
end
